config/routes.rb
Rails.application.routes.draw do

  resources :messages

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts, :only => [:index, :show]

  devise_for :users
  root :to => 'homepage#index'
  get '/about' => 'homepage#about'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

   user ||= User.new # guest user (not logged in)
   if user.admin?
     can :access, :rails_admin   # grant access to rails_admin
     can :manage, :all
     can :dashboard              # grant access to the dashboard
   else
     can :read, [Post, About]
   end

  end
end

app/models/about.rb
class About < ActiveRecord::Base
  rails_admin do
    
    list do
      field :title
      field :created_at
    end

    create do
      field :title do
        help 'Please select a Title'
      end
      field :body, :text do
        html_attributes do
          {rows: 20, cols: 70}
        end
      end
    end

    edit do
      field :title do
        help 'Please select a Title'
      end
      field :body, :text do
        html_attributes do
          {rows: 20, cols: 80}
        end
      end
    end
    
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  
  # Model validations
  validates :to, presence: true
  validates :body, presence: true

  after_create :process_sms

  # get the twilio sid
  def self.twilio_sid
    Rails.application.secrets.twilio_sid
  end

  # get the twilio secret token
  def self.twilio_secret
    Rails.application.secrets.twilio_secret
  end

  # initialize the client
  def self.twilio_client
    @client = Twilio::REST::Client.new twilio_sid, twilio_secret
  end

  # my current number
  def self.my_number
    Rails.application.secrets.my_number
  end

  def self.default_number
    Rails.application.secrets.twilio_number
  end

  def self.send_sms(to, body, from = default_number)
    twilio_client.account.messages.create({
        :from => from,
        :to => to,
        :body => body
    })
  end

  def process_sms
    Message.send_sms(to, body)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  rails_admin do
    
    list do
      field :title
      field :created_at
    end

    create do
      field :title do
        help 'Please select a Title'
      end
      field :content, :text do
        html_attributes do
          {rows: 20, cols: 70}
        end
      end
    end

    edit do
      field :title do
        help 'Please select a Title'
      end
      field :content, :text do
        html_attributes do
          {rows: 20, cols: 80}
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :company_name, :phone, :email, :password, :password_confirmation) }
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end

  def about
    @about = About.last
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:to, :from, :body, :sms_id, :sms_status)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc).all.page(params[:page]).per(20)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    render_options = {
      # will remove from the output HTML tags inputted by user 
      filter_html:   false,
      # will insert <br /> tags in paragraphs where are newlines 
      # (ignored by default)
      hard_wrap:       true, 
      # hash for extra link options, for example 'nofollow'
      link_attributes: { rel: 'nofollow' }
      # more
      # will remove <img> tags from output
      # no_images: true
      # will remove <a> tags from output
      # no_links: true
      # will remove <style> tags from output
      # no_styles: true
      # generate links for only safe protocols
      # safe_links_only: true
      # and more ... (prettify, with_toc_data, xhtml)
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
      #will parse links without need of enclosing them
      autolink:           true,
      # blocks delimited with 3 ` or ~ will be considered as code block. 
      # No need to indent.  You can provide language name too.
      # ```ruby
      # block of code
      # ```
      fenced_code_blocks: true,
      # will ignore standard require for empty lines surrounding HTML blocks
      lax_spacing:        true,
      # will not generate emphasis inside of words, for example no_emph_no
      no_intra_emphasis:  true,
      # will parse strikethrough from ~~, for example: ~~bad~~
      strikethrough:      true,
      # will parse superscript after ^, you can wrap superscript in () 
      superscript:        true
      # will require a space after # in defining headers
      # space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/mail_helper.rb
module MailHelper
end

app/views/homepage/about.haml
- meta title: "Lorenzo Sinisi - " + @about.title, description: @about.body, keywords: %w(ruby fullstack rails)
.the_time
  = DateTime.now.utc
%h1= @about.title
%hr
%p= @about.body.html_safe

app/views/homepage/index.haml
- meta title: "Lorenzo Sinisi - Ruby Developer", description: "Fullstack Ruby Developer", keywords: %w(ruby fullstack rails)
.container-home
 .header-full
  %h1 Lorenzo Sinisi - Ruby Developer
  %hr
  %p Fullstack Ruby Developer
  %p I've been working in Italy and Germany and I have experience as Fullstack Ruby Developer in Consultancy, IoT and SaaS companies. I have a business background that is why I make decisions based on both business and tech perspective; that's what often prefer when working with me.
  %p= link_to "Read more & links >> ", about_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = metamagic
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"
    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular-resource.min.js"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    = javascript_include_tag "application"
    <link href='http://fonts.googleapis.com/css?family=Anonymous+Pro:700,400,700italic,400italic' rel='stylesheet' type='text/css'>
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand
          =image_tag  "logo.png", :class => "logo-img shake shake-slow"
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "HOME", "/"
            %li= link_to "ABOUT", "/about"
            %li= link_to "POSTS", posts_path
    .container
      .terminal
        - if user_signed_in?
          = link_to('Logout ' + current_user.email, destroy_user_session_path, :method => :delete)
        .row.content
          = bootstrap_flash
          = yield
      %footer
        %p &copy; #{Date.today.year} - (C) Lorenzo Sinisi - Created with ♥ in Italy

app/views/messages/_form.html.haml
= semantic_form_for @message do |f|
  = f.inputs do
    = f.input :to
    = f.input :from
    = f.input :body

  = f.actions do
    = f.action :submit, :as => :input

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %thead
    %tr
      %th To
      %th From
      %th Body
      %th
      %th
      %th

  %tbody
    - @messages.each do |message|
      %tr
        %td= message.to
        %td= message.from
        %td= message.body
        %td= link_to 'Show', message
        %td= link_to 'Edit', edit_message_path(message)
        %td= link_to 'Destroy', message, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

= link_to 'New Message', new_message_path, class: "btn btn-success"

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b To:
  = @message.to
%p
  %b From:
  = @message.from
%p
  %b Body:
  = @message.body
%p
  %b Sms:
  = @message.sms_id
%p
  %b Sms status:
  = @message.sms_status

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path

app/views/posts/index.html.haml
- meta title: "Lorenzo Sinisi - Posts", description: "Articles by Lorenzo Sinisi - Ruby Developer", keywords: %w(ruby fullstack rails)
%h1 Archive:

- @posts.each do |post|
  %content
    %h2= post.title
    .content= simple_format(post.content)
    %span(data-no-turbolink)= link_to 'Read more >>', post
  %hr
= paginate @posts

app/views/posts/show.html.haml
- meta title: @post.title, keywords: %w(ruby fullstack rails)
%p#notice= notice
%content
  %h2= @post.title
  .content= markdown @post.content
  %hr
= link_to 'Back', posts_path